
import { Recommendation, VibeFilter } from "../types";

export const mockRecommendations: Recommendation[] = [
  {
    recommendationId: "1",
    name: "The Hidden Speakeasy",
    address: "123 Secret St, Downtown",
    type: "bar",
    vibeTags: ["cocktails", "intimate", "live jazz", "date night"],
    socialSentimentScore: 0.92,
    latitude: 40.7589,
    longitude: -73.9851,
    timestamp: new Date().toISOString(),
    description: "A cozy underground bar with craft cocktails and live jazz every Friday. Perfect for intimate conversations.",
    priceRange: "$$$",
    openNow: true,
  },
  {
    recommendationId: "2",
    name: "Sunrise Rooftop Cafe",
    address: "456 Sky Ave, Midtown",
    type: "cafe",
    vibeTags: ["rooftop", "coffee", "sunset views", "instagrammable"],
    socialSentimentScore: 0.88,
    latitude: 40.7614,
    longitude: -73.9776,
    timestamp: new Date().toISOString(),
    description: "Amazing city views and artisanal coffee. Popular spot for watching sunsets and taking photos.",
    priceRange: "$$",
    openNow: true,
  },
  {
    recommendationId: "3",
    name: "Underground Eats",
    address: "789 Basement Blvd, East Side",
    type: "restaurant",
    vibeTags: ["fusion", "trendy", "small plates", "buzzing"],
    socialSentimentScore: 0.85,
    latitude: 40.7505,
    longitude: -73.9934,
    timestamp: new Date().toISOString(),
    description: "Innovative fusion cuisine in a converted subway station. Always packed with food enthusiasts.",
    priceRange: "$$$$",
    openNow: false,
  },
  {
    recommendationId: "4",
    name: "Vinyl & Vibes",
    address: "321 Music Row, Arts District",
    type: "bar",
    vibeTags: ["live music", "vinyl records", "craft beer", "alternative"],
    socialSentimentScore: 0.90,
    latitude: 40.7282,
    longitude: -73.9942,
    timestamp: new Date().toISOString(),
    description: "Record store by day, live music venue by night. Great selection of craft beers and emerging artists.",
    priceRange: "$$",
    openNow: true,
  },
];

export const mockVibeFilters: VibeFilter[] = [
  { id: "live-music", label: "Live Music", emoji: "🎵", active: false },
  { id: "rooftop", label: "Rooftop", emoji: "🏙️", active: false },
  { id: "cocktails", label: "Cocktails", emoji: "🍸", active: false },
  { id: "coffee", label: "Coffee", emoji: "☕", active: false },
  { id: "date-night", label: "Date Night", emoji: "💕", active: false },
  { id: "group-friendly", label: "Groups", emoji: "👥", active: false },
  { id: "outdoor", label: "Outdoor", emoji: "🌳", active: false },
  { id: "trendy", label: "Trendy", emoji: "✨", active: false },
];
